In [2]:
## Data set tip from seaborn
import seaborn as sns
df=sns.load_dataset('tips')

In [3]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [5]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [6]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [7]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [8]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [10]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [11]:
#independent and dependent features
X=df[['tip', 'sex', 'smoker', 'day', 'time', 'size']]
y=df['total_bill']

In [33]:
#train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [34]:
X_train.head()

      tip     sex smoker  day    time  size
115  3.50  Female     No  Sun  Dinner     2
181  5.65    Male    Yes  Sun  Dinner     2
225  2.50  Female    Yes  Fri   Lunch     2
68   2.01    Male     No  Sat  Dinner     2
104  4.08  Female     No  Sat  Dinner     2

Feature encoding(label encoding,one hot encoding)

In [14]:
#label encoding:when we have only two categories in a feature then we can use label encoding
#one hot encoding:when we have more than two categories in a feature then we can use one hot encoding

In [35]:
from sklearn.preprocessing import LabelEncoder

In [36]:
le1=LabelEncoder()
le2=LabelEncoder()
le3=LabelEncoder()

In [37]:
X_train['sex']=le1.fit_transform(X_train['sex'])
X_train['smoker']=le2.fit_transform(X_train['smoker'])
X_train['time']=le3.fit_transform(X_train['time'])

In [38]:
X_train.head()

      tip  sex  smoker  day  time  size
115  3.50    0       0  Sun     0     2
181  5.65    1       1  Sun     0     2
225  2.50    0       1  Fri     1     2
68   2.01    1       0  Sat     0     2
104  4.08    0       0  Sat     0     2

In [39]:
X_test['sex']=le1.transform(X_test['sex'])
X_test['smoker']=le2.transform(X_test['smoker'])
X_test['time']=le3.transform(X_test['time'])

In [40]:
X_test.head()

      tip  sex  smoker   day  time  size
24   3.18    1       0   Sat     0     2
6    2.00    1       0   Sun     0     2
153  2.00    1       0   Sun     0     4
211  5.16    1       1   Sat     0     4
198  2.00    0       1  Thur     1     2

In [ ]:
#one hot encoding for the day-- applied by column transformer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder